# Generated by Django 3.1.2 on 2020-10-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('front_normal_image', models.CharField(max_length=100)),
                ('front_shiny_image', models.CharField(max_length=100)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('ability_One', models.CharField(max_length=40)),
                ('ability_Two', models.CharField(max_length=40)),
                ('type_One', models.CharField(max_length=40)),
                ('type_Two', models.CharField(max_length=40)),
            ],
        ),
    ]
