# Generated by Django 3.1.2 on 2020-10-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemontrainer',
            name='displayname',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
