# Generated by Django 3.1.2 on 2020-10-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemontrainer',
            name='pokedexed',
            field=models.ManyToManyField(related_name='pokemon_indexed', to='mainapp.Pokemon'),
        ),
    ]
