# Generated by Django 3.1.2 on 2020-10-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201007_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemontrainer',
            name='pokedexed',
            field=models.ManyToManyField(blank=True, related_name='pokemon_indexed', to='mainapp.Pokemon'),
        ),
    ]
