# Generated by Django 3.1 on 2020-10-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201007_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='details_at',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='your_thoughts',
        ),
    ]
