# Generated by Django 3.1.2 on 2020-10-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201008_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='special_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_defense',
            field=models.IntegerField(default=0),
        ),
    ]
